name: Drupi
api: "1.0.0"
main: hundeklemmen.main
author: Hundeklemmen
version: "0.1.0.4"
description: js scripting in bedrock
softdepend: [PlaceholderAPI]
commands:
  drupi:
    description: Interacting with the plugin
    usage: /drupi [args]