name: "Drupi"
api: "1.0.0"
main: hundeklemmen.minehut.MainPlugin
author: Hundeklemmen
version: "0.1.2-minehut"
description: JavaScripting in Minecraft!
softdepend: [PlaceholderAPI, Vault, WorldGuard, Holograms]
commands:
  drupi:
    description: Interacting with the plugin
    usage: /drupi [args]