name: Drupi
api: "1.0.0"
main: hundeklemmen.legacy.MainPlugin
author: Hundeklemmen
version: "0.1.0"
description: js scripting in spigot
softdepend: [PlaceholderAPI, Vault, WorldGuard]
commands:
  drupi:
    description: Interacting with the plugin
    usage: /drupi [args]