name: Drupi
api: "1.0.0"
main: hundeklemmen.legacy.MainPlugin
author: ["Hundeklemmen", "Stacket"]
version: "0.3.2"
description: "Minecraft development made easy."
website: "https://stacket.net/drupi"
softdepend: [PlaceholderAPI, WorldGuard, Holograms, Skript, TitleManager, LabyModAPI]
commands:
  drupi:
    description: Interacting with the plugin
    usage: /drupi [args]