name: Drupi
main: hundeklemmen.bungeecord.MainPlugin
version: "0.4.5"
author: "Hundeklemmen"
description: "Minecraft development made easy."
website: "https://stacket.net/drupi"
softdepend: [LabyModAPI]